# fly.toml app configuration file generated for young-mountain-67 on 2023-05-22T20:57:59-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "young-mountain-67"
primary_region = "ord"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0

[env]
  PORT = "8080" # add this
